name: Build/release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install rpm if necessary
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install rpm

      - name: Install packages
        working-directory: ./app
        run: npm install

      - name: Install Renderer Packages
        working-directory: ./app/src/renderer
        run: npm install

      - name: Publish Build to Github
        working-directory: ./app
        run: npm run publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
